# Lab 9 - Deployment Kubernetes
# Este manifesto cria 3 replicas de uma aplicacao Nginx simples.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
