apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-config
  namespace: hotel-system
data:
  NODE_ENV: production
  NODE_WEB_PORT: "3000"
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: gestao_hotel
  POSTGRES_USER: hotel_user
  REDIS_URL: "redis://redis:6379"
